Crypto/keyboard cypher
michiganhackers/security_2022 pull request #2
Opened 2021-10-07 23:36 UTC by pnhalim

We created a challenge called keyboard_cypher

2021-10-12 02:01 UTC, jushutch commented
This challenge looks great, neat encryption method! What is the rtf file for and did you mean to add two? There's one outside your challenge directory which probably needs to be removed.

2021-10-28 21:01 UTC, jushutch requested changes
You'll need to remove the keyboardcypher.rtf file from the crypto directory.

2021-10-29 18:43 UTC, jushutch approved these changes

2021-11-03 03:44 UTC, anisha2442 approved these changes
Looks great! Creative cipher

2021-11-04 22:43 UTC, merged